all:
	@echo -e "\033[33m< Generating Doc >\033[37m"
	@doxygen config		1>/dev/null
	@echo -e "\033[33m< Doc generated >\033[37m"

clean:
	@echo -e "\033[34m< Cleaning Doc >\033[37m"
	@rm -rf html latex

